### PR TITLE
Add quarkus-jgit and quarkus-jsch

### PR DESCRIPTION
**Pull request by gsmet**
@gastaldi I will try to move JGit while things are fresh and I can improve my check list. Could you check if I did everything right?

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
This looks great! You need to migrate `quarkus-jsch` too as it's used by Camel and the JGit extensions

**Comment by gastaldi** [comment]
I added the missing branch definition (as mentioned in https://github.com/quarkiverse/quarkiverse-devops#workflow-for-new-repositories)

**Comment by gsmet** [comment]
Hmm OK, let me add jsch.

**Comment by gsmet** [comment]
I added jsch.

I'm not sure though it's worth defining the default branch given the instructions from GitHub makes you use main as the default branch and wires everything automatically.

**Comment by gastaldi** [comment]
I remember having some trouble if that's not defined in other repository, but maybe that was a user's mistake

**Comment by gsmet** [comment]
@gastaldi I'll let you merge this once you think everything is OK :).

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
