### PR TITLE
Add new repositories for migration from Core

### PR DESCRIPTION
**Pull request by gastaldi**
Supersedes #12

### CODE REVIEW

**Comment by gsmet** [comment]
Ah thanks, I was doing it too :)

**Review by gsmet — APPROVED** [review]
I don't know who did this work but it looks amazing!

**Comment by gsmet** [comment]
@gastaldi I let you merge it when you think things are good!

**Comment by gastaldi** [comment]
It looks great! I noticed the quarkus-lucene extension maintainer @gustavonalle renamed his ID to @gustavocoding, so I need to update the script here too. Merging now. Thanks!

**Pull request merged**
