### PR TITLE
Add @shivam-sharma7 to quarkus-quinoa

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@gastaldi Is there any problem with PR? You are pushing again and again because I got 15+ notification 😉

**Comment by gastaldi** [comment]
Sorry about that, I am performing some changes in the GitHub Actions workflow and using this PR to test. It should be fine now

**Comment by gastaldi** [comment]
@shivam-sharma7 I'll wait until one of the team members in @quarkiverse/quarkiverse-quinoa approves this PR before merging it

**Comment by shivam-sharma7** [comment]
@melloware can you approve?

**Comment by shivam-sharma7** [comment]
@melloware @ia3andy may you approve this?

**Review by melloware — APPROVED** [review]

**Comment by ia3andy** [comment]
Congrats @shivam-sharma7 :)

**Comment by shivam-sharma7** [comment]
Thanks team!

**Pull request merged**
