### PR TITLE
Install LGTM to Quarkus Open API Extension

### PR DESCRIPTION
**Pull request by ricardozanini**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by ricardozanini** [comment]
@gastaldi do you know what's wrong with my file?

**Comment by gastaldi** [comment]
Does it change when you run `terraform fmt`

**Comment by ricardozanini** [comment]
> Does it change when you run `terraform fmt`?

I'll have to install it locally then.

**Comment by ricardozanini** [comment]
@gastaldi we have the greenlight! :D

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
